
vars = {...
    'D',...
'WQ_OXY_OXY',...
'WQ_SIL_RSI',...
'WQ_NIT_AMM',...
'WQ_NIT_NIT',...
'WQ_PHS_FRP',...
'WQ_PHS_FRP_ADS',...
'WQ_OGM_DOC',...
'WQ_OGM_POC',...
'WQ_OGM_DON',...
'WQ_OGM_PON',...
'WQ_OGM_DOP',...
'WQ_OGM_POP',...
'WQ_PHY_CYANO',...
'WQ_PHY_CHLOR',...
'WQ_PHY_CRYPT',...
'WQ_PHY_EDIAT',...
'WQ_PHY_LDIAT',...
'WQ_DIAG_TOT_TN',...
'WQ_DIAG_TOT_TP',...
'WQ_DIAG_PHY_TCHLA',...
'WQ_DIAG_MAG_TMALG',...
    };
