%% define vars in processing

% 3D vars name for C pool
NPool_3D={'WQ_OGM_DOP',...
    'WQ_OGM_POP',...
    'WQ_PHS_FRP',...
    'WQ_PHS_FRP_ADS',...
    'WQ_DIAG_PHY_IP',...
    };
NPool_3D_factors=[1 1 1 1 1]*31/1e9;

% 2D vars name for C pool
NPool_2D={'WQ_DIAG_MAG_IP_BEN',...
    'MAG_SLOUGHXPC',...
    'MPB_BENXPC',...
    };
NPool_2D_factors=[1 1 1]*31/1e9;

% 3D vars name for C BGC process
N_BGC_3D={'WQ_DIAG_OGM_POP_SET',...
    'WQ_DIAG_PHY_UPT_PO4'          ,...
    'WQ_DIAG_OGM_POP_HYD',...
    'WQ_DIAG_OGM_DOP_MIN',...
    'PHY_SETXPC',...
    };
%     'WQ_DIAG_PHY_DINO_MOR_N',...
%     'WQ_DIAG_PHY_DIATOM_MOR_N',...
%     'WQ_DIAG_PHY_CRYPT_MOR_N',...
%     'WQ_DIAG_PHY_GRN_MOR_N',...
%     'WQ_DIAG_PHY_DINO_EXC_N',...
%     'WQ_DIAG_PHY_DIATOM_EXC_N',...
%     'WQ_DIAG_PHY_CRYPT_EXC_N',...
%     'WQ_DIAG_PHY_GRN_EXC_N',...

N_BGC_3D_factors=[1 1 1 1 1 1 1 1 1]*31/1e9;

% 2D vars name for BGC process
N_BGC_2D={'WQ_DIAG_OGM_POP_SWI',...
    'WQ_DIAG_OGM_DOP_SWI',...
    'WQ_DIAG_PHS_FRP_DSF',...
    'MAG_SLOUGHXPC',... %  % use slough instead
    'WQ_DIAG_MAG_MAG_SWI_P',...
    'WQ_DIAG_PHY_PHY_SWI_P',...
    'WQ_DIAG_MAG_PUP_BEN',...    % WQ_DIAG_MAG_GPP_BEN',...
    };
N_BGC_2D_factors=[1 1 1 1 1 1 1]*31/1e9;
%N_BGC_2D_perSecond={...
%    'WQ_DIAG_PHY_PSED_PHY',...
%    'WQ_DIAG_OGM_PSED_PON',...
%    };

%% plotting setting

% all C pool var names in the plot
NPool_vars ={'WQ_PHS_FRP',...
    'WQ_PHS_FRP_ADS',...
    'WQ_OGM_DOP',...
    'WQ_OGM_POP',...
    'WQ_DIAG_MAG_IP_BEN',...
    'WQ_DIAG_PHY_IP',...
    };

% names to display in the plot
NPool_names={'$${PO_4^{3-}}$$',...
    '$${PO_4^{ads}}$$',...
    '$${DOP}$$',...
    '$${POP}$$',...
    '$${MAG\_{ip}}$$',...
    '$${PHY\_{ip}}$$',...
    };

% factors to convert biomass to N
NPool_factors=[1 1 1 1 1 1];

% color scheme for each variables
NPool_colors=[252,141,89;...
    67,162,202;...
    8,81,156;...
    0,109,44;...
    44,162,95;...
    102,194,164];

%    227,74,51;...

%% all BGC process var names in the plot
N_BGC_vars ={'WQ_DIAG_PHS_FRP_DSF',...
    'WQ_DIAG_OGM_DOP_SWI',...
    'WQ_DIAG_OGM_POP_SWI',...
    'WQ_DIAG_PHY_PHY_SWI_P',...
    'MAG_SLOUGHXPC',... %'WQ_DIAG_MAG_MAG_SWI_P',...
    };

% names to display in the plot
N_BGC_names={...
    '$${{\mathcal{F}}_{sed}^{frp}}$$',...
    '$${{\mathcal{F}}_{swi}^{dop}}$$',...
    '$${{\mathcal{F}}_{swi}^{pop}}$$',...
    '$${{\hat{f}}_{swi}^{MPBp}}$$',...
    '$${{\hat{f}}_{slough}^{MAGp}}$$',...
    };

N_BGC_signs=[1 1 1 1 1 1];
N_BGC_factors=[1 1 1 1 1 1];

% color scheme for each variables
N_BGC_colors=[67,162,202;...
    227,74,51;...
    253,187,132;...
    191,211,230;...
140,150,198;...
44,162,95;...
136,86,167;...
129,15,124];

%% all internal BGC process var names in the plot
N_intBGC_vars ={'FRP_uptake',...
    'WQ_DIAG_MAG_PUP_BEN',...
    };

% names to display in the plot
N_intBGC_names={...
    '$${f_{upt_{P}}^{PHY}}$$',...
    '$${f_{upt_{P}}^{MAG}}$$',...
    };

N_intBGC_signs=[1 -1 1 1];
N_intBGC_factors=[1 1 1 1];

% color scheme for each variables
N_intBGC_colors=[67,162,202;...
    227,74,51;...
    253,187,132;...
    191,211,230;...
140,150,198;...
44,162,95;...
136,86,167;...
129,15,124];
%%
% all BGC process var names in the plot
Nsed_vars ={'FRP_release',...
    'WQ_DIAG_OGM_POP_SWI',...
    'WQ_DIAG_MAG_MAG_SWI_P',...
    'WQ_DIAG_PHY_PHY_SWI_P',...
    };

% names to display in the plot
Nsed_names={...
    'sed release',...
    'POP swi',...
    'mag swi',...
    'phy swi',...
    };

Nsed_signs=[1 1 1 1 1];
Nsed_factors=[1 1 1 1 1];

% color scheme for each variables
Nsed_colors=[166,206,227;...
    31,120,180;...
    178,223,138;...
    51,160,44;...
    251,154,153;...
    227,26,28;...
    253,191,111;...
    255,127,0;...
    202,178,214;...
    106,61,154];


%%
N_flux_vars ={'OGM_don',...
    'OGM_pon',...
    'NIT_nit',...
    'NIT_amm',...
    'PHY_grn',...
    'PHY_diatom',...
    'PHY_crypt',...
    'PHY_dino',...
    'MA2_ulva_IN',...
    };

N_flux_names={'IP',...
    'OP',...
    'PPP'};

N_flux_names2={'$${F_{T}^{{PO_4^{3-}}}}+{F_{T}^{{PO_4^{ads}}}}$$',...
    '$${F_{T}^{DOP}}+{F_{T}^{POP}}$$',...
    '$${F_{T}^{PHY\_ip}}+{F_{T}^{MAG\_ip}}$$'};

N_flux_colors=[252,141,89;...
    67,162,202;...
    0,109,44;...
    ];