%% define vars in processing

% 3D vars name for C pool
NPool_3D={'WQ_OGM_DON',...
    'WQ_OGM_PON',...
    'WQ_NIT_NIT',...
    'WQ_NIT_AMM',...
    'WQ_DIAG_PHY_IN',...
    };
NPool_3D_factors=[1 1 1 1 1 1]*14/1e9;

% 2D vars name for C pool
NPool_2D={'WQ_DIAG_MAG_IN_BEN',...
    'MAG_SLOUGHXNC',...
    'MPB_BENXNC',...
    };
NPool_2D_factors=[1 1 1]*14/1e9;

% 3D vars name for C BGC process
N_BGC_3D={'WQ_DIAG_NIT_DENIT',...
    'WQ_DIAG_OGM_PON_SET',...
    'WQ_DIAG_PHY_UPT_NO3'          ,...
    'WQ_DIAG_PHY_UPT_NH4'          ,...
    'WQ_DIAG_NIT_NITRIF'           ,...
    'WQ_DIAG_OGM_PON_HYD',...
    'WQ_DIAG_OGM_DON_MIN',...
    'PHY_SETXNC',...
    };
%     'WQ_DIAG_PHY_DINO_MOR_N',...
%     'WQ_DIAG_PHY_DIATOM_MOR_N',...
%     'WQ_DIAG_PHY_CRYPT_MOR_N',...
%     'WQ_DIAG_PHY_GRN_MOR_N',...
%     'WQ_DIAG_PHY_DINO_EXC_N',...
%     'WQ_DIAG_PHY_DIATOM_EXC_N',...
%     'WQ_DIAG_PHY_CRYPT_EXC_N',...
%     'WQ_DIAG_PHY_GRN_EXC_N',...

N_BGC_3D_factors=[1 1 1 1 1 1 1 1 1 1 1 1]*14/1e9;

% 2D vars name for BGC process
N_BGC_2D={'WQ_DIAG_OGM_PON_SWI',...
    'WQ_DIAG_OGM_DON_SWI',...
    'WQ_DIAG_NIT_AMM_DSF',...
    'WQ_DIAG_NIT_NIT_DSF',...
    'WQ_DIAG_MAG_MAG_SWI_N',...
    'WQ_DIAG_PHY_PHY_SWI_N',...
    'WQ_DIAG_MAG_NUP_BEN',...
    };
N_BGC_2D_factors=[1 1 1 1 1 1 1 1]*14/1e9;
%N_BGC_2D_perSecond={...
%    'WQ_DIAG_PHY_PSED_PHY',...
%    'WQ_DIAG_OGM_PSED_PON',...
%    };

%% plotting setting

% all C pool var names in the plot
NPool_vars ={'WQ_NIT_NIT',...
    'WQ_NIT_AMM',...
    'WQ_OGM_DON',...
    'WQ_OGM_PON',...
    'WQ_DIAG_MAG_IN_BEN',...
    'WQ_DIAG_PHY_IN',...
    };

% names to display in the plot
NPool_names={'$${NO_3^-}$$',...
    '$${NH_4^+}$$',...
    '$${DON}$$',...
    '$${PON}$$',...
    '$${MAG\_{in}}$$',...
    '$${PHY\_{in}}$$',...
    };

% factors to convert biomass to N
NPool_factors=[1 1 1 1 1 1];

% color scheme for each variables
NPool_colors=[252,141,89;...
    227,74,51;...
    67,162,202;...
    8,81,156;...
    0,109,44;...
    44,162,95;...
    102,194,164];



%% all BGC process var names in the plot
N_BGC_vars ={'WQ_DIAG_NIT_AMM_DSF',...
    'WQ_DIAG_NIT_NIT_DSF',...
    'WQ_DIAG_OGM_DON_SWI',...
    'WQ_DIAG_OGM_PON_SWI',...
    'WQ_DIAG_PHY_PHY_SWI_N',...
    'MAG_SLOUGHXNC',... %'WQ_DIAG_MAG_MAG_SWI_N',...
    };
% .WQ_DIAG_NIT_AMM_DSF+data.WQ_DIAG_OGM_DON_SWI;
%     data.NIT_denit=data.WQ_DIAG_NIT_NIT_DSF-data.WQ_DIAG_NIT_DENIT;
%     data.NIT_burial=data.WQ_DIAG_MAG_MAG_SWI_N+data.WQ_DIAG_PHY_PHY_SWI_N
% names to display in the plot
N_BGC_names={...
    '$${{\mathcal{F}}_{sed}^{nh4}}$$',...
    '$${{\mathcal{F}}_{sed}^{no3}}$$',...
    '$${{\mathcal{F}}_{swi}^{don}}$$',...
    '$${{\mathcal{F}}_{swi}^{pon}}$$',...
    '$${{\hat{f}}_{swi}^{MPBn}}$$',...
    '$${{\hat{f}}_{slough}^{MAGn}}$$',...
    };

N_BGC_signs=[1 1 1 1 1 1];
N_BGC_factors=[1 1 1 1 1 1];

% color scheme for each variables
N_BGC_colors=[67,162,202;...
    227,74,51;...
    253,187,132;...
    191,211,230;...
140,150,198;...
44,162,95;...
136,86,167;...
129,15,124];

%% all internal BGC process var names in the plot
N_intBGC_vars ={'NIT_uptake',...
    'WQ_DIAG_MAG_NUP_BEN',...
    'WQ_DIAG_NIT_DENIT',...
    };

% names to display in the plot
N_intBGC_names={...
    '$${f_{upt_{N}}^{PHY}}$$',...
    '$${f_{upt_{N}}^{MAG}}$$',...
    '$${{\mathcal{F}}_{denit}^{NO3}}$$',...
    };

N_intBGC_signs=[1 -1 1];
N_intBGC_factors=[1 1 1];

% color scheme for each variables
N_intBGC_colors=[67,162,202;...
    227,74,51;...
    253,187,132;...
    191,211,230;...
140,150,198;...
44,162,95;...
136,86,167;...
129,15,124];
%%
% all BGC process var names in the plot
Nsed_vars ={'NIT_release',...
    'WQ_DIAG_OGM_PON_SWI',...
    'WQ_DIAG_MAG_MAG_SWI_N',...
    'WQ_DIAG_PHY_PHY_SWI_N',...
    };

% names to display in the plot
Nsed_names={...
    'sed release',...
    'PON swi',...
    'mag swi',...
    'phy swi',...
    };

Nsed_signs=[1 1 1 1 1];
Nsed_factors=[1 1 1 1 1];

% color scheme for each variables
Nsed_colors=[166,206,227;...
    31,120,180;...
    178,223,138;...
    51,160,44;...
    251,154,153;...
    227,26,28;...
    253,191,111;...
    255,127,0;...
    202,178,214;...
    106,61,154];


%%
N_flux_vars ={'OGM_don',...
    'OGM_pon',...
    'NIT_nit',...
    'NIT_amm',...
    'PHY_grn',...
    'PHY_diatom',...
    'PHY_crypt',...
    'PHY_dino',...
    'MA2_ulva_IN',...
    };

N_flux_names={'IN',...
    'ON',...
    'PPN'};

N_flux_names2={'$${F_{T}^{{NO_3^-}}}+{F_{T}^{{NH_4^+}}}$$',...
    '$${F_{T}^{DON}}+{F_{T}^{PON}}$$',...
    '$${F_{T}^{PHY\_in}}+{F_{T}^{MAG\_in}}$$'};

N_flux_colors=[252,141,89;...
    67,162,202;...
    0,109,44;...
    ];