
vars = {...
    'D',...
    'WQ_DIAG_TOT_TN'               ,...
    'WQ_NIT_AMM'                   ,...
    'WQ_NIT_NIT'                   ,...
    'WQ_DIAG_NIT_AMM_DSF',...
    'WQ_DIAG_NIT_NIT_DSF',...
    'WQ_DIAG_NIT_SED_AMM'          ,...
    'WQ_DIAG_NIT_SED_NIT'          ,...
    'WQ_DIAG_NIT_NITRIF'           ,...
    'WQ_DIAG_NIT_DENIT'            ,...
    'WQ_DIAG_NIT_ANAMMOX'          ,...
    'WQ_DIAG_NIT_DNRA'             ,...
    'WQ_DIAG_NIT_DIN_ATM'     ,...
    'WQ_DIAG_OGM_PON_SET',...
    'WQ_DIAG_OGM_PON_RES',...
    'WQ_DIAG_OGM_PON_HYD',...
    'WQ_DIAG_OGM_DON_MIN',...
    'WQ_DIAG_OGM_PON_SWI',...
    'WQ_DIAG_OGM_DON_SWI',...
    'WQ_DIAG_OGM_PON_RES',...
    'WQ_DIAG_OGM_DOC_DENIT',...
    'WQ_DIAG_OGM_DOC_ANAEROBIC',...
    'WQ_OGM_DON'                   ,...
    'WQ_OGM_PON'                   ,...
    };