
vars = {...
    'D',...
%     'WQ_DIAG_TOT_TN'               ,...
%     'WQ_OGM_DON'                   ,...
%     'WQ_OGM_PON'                   ,...
%     'WQ_NIT_AMM'                   ,...
%     'WQ_NIT_NIT'                   ,...
%     'WQ_DIAG_OGM_PON_SET',...
%     'WQ_DIAG_OGM_PON_RES',...
%     'WQ_DIAG_OGM_PON_HYD',...
%     'WQ_DIAG_OGM_DON_MIN',...
%     'WQ_DIAG_OGM_PON_SWI',...
%     'WQ_DIAG_OGM_DON_SWI',...
%     'WQ_DIAG_OGM_PON_RES',...
%     'WQ_DIAG_NIT_AMM_DSF',...
%     'WQ_DIAG_NIT_NIT_DSF',...
%     'WQ_DIAG_NIT_SED_AMM'          ,...
%     'WQ_DIAG_NIT_SED_NIT'          ,...
%     'WQ_DIAG_NIT_NITRIF'           ,...
%     'WQ_DIAG_NIT_DENIT'            ,...
%     'WQ_DIAG_NIT_ANAMMOX'          ,...
%     'WQ_DIAG_NIT_DNRA'             ,...
%     'WQ_DIAG_NIT_DIN_ATM'     ,...
%     'WQ_DIAG_TOT_TP'               ,...
%     'WQ_OGM_DOP'                   ,...
%     'WQ_OGM_POP'                   ,...
%     'WQ_PHS_FRP'                   ,...
%     'WQ_PHS_FRP_ADS'               ,...
%     'WQ_DIAG_OGM_POP_HYD',...
%     'WQ_DIAG_OGM_DOP_MIN',...
%     'WQ_DIAG_OGM_POP_SWI',...
%     'WQ_DIAG_OGM_DOP_SWI',...
%     'WQ_DIAG_OGM_POP_RES',...
%     'WQ_DIAG_PHS_FRP_DSF',...
%     'WQ_DIAG_PHS_SED_FRP'          ,...
%     'WQ_DIAG_PHS_DIP_ATM'     ,...
%     'WQ_DIAG_PHY_TCHLA'            ,...
%     'WQ_PHY_GRN'                   ,...
%     'WQ_PHY_CRYPT'                   ,...
%     'WQ_PHY_DIATOM'                   ,...
%     'WQ_PHY_DINO'                   ,...
%     'WQ_DIAG_PHY_GPP'              ,...
%     'WQ_DIAG_PHY_NCP',...
%     'WQ_DIAG_PHY_UPT_NO3'          ,...
%     'WQ_DIAG_PHY_UPT_NH4'          ,...
%     'WQ_DIAG_PHY_UPT_PO4',...
%     'WQ_DIAG_OGM_DOC_DENIT',...
%     'WQ_DIAG_OGM_POP_SET',...
%     'WQ_DIAG_PHS_DIP_ATM'     ,...
%     'WQ_DIAG_PHY_DINO_SET_P',...
%     'WQ_DIAG_PHY_DIATOM_SET_P',...
%     'WQ_DIAG_PHY_CRYPT_SET_P',...
%     'WQ_DIAG_PHY_GRN_SET_P',...
%     'WQ_DIAG_PHY_IP',...
%     'WQ_DIAG_PHY_MPB_SWI',...
%     'WQ_DIAG_PHY_MPB_GPP',...
%     'WQ_DIAG_PHY_MPB_RSP',...
%     'WQ_DIAG_PHY_MPB_BEN',...
%     'WQ_DIAG_PHY_MPB_RES',...
%     'WQ_DIAG_PHY_PHY_SWI_C',...
%     'WQ_DIAG_PHY_PHY_SWI_N',...
%     'WQ_DIAG_PHY_PHY_SWI_P',...
%     'WQ_DIAG_PHY_SET',...
%     'WQ_DIAG_PHY_RES',...
%     'WQ_DIAG_PHY_MPB_XNC',...
%     'WQ_DIAG_PHY_MPB_XPC',...
%     'WQ_DIAG_PHY_DINO_SET_N',...
%     'WQ_DIAG_PHY_DIATOM_SET_N',...
%     'WQ_DIAG_PHY_CRYPT_SET_N',...
%     'WQ_DIAG_PHY_GRN_SET_N',...
%     'WQ_DIAG_PHY_IN',...
%     'WQ_DIAG_PHY_TPHY',...
%     'WQ_DIAG_PHY_UPT_NO3'          ,...
%     'WQ_DIAG_PHY_UPT_NH4'          ,...
%     'WQ_DIAG_MAG_MAG_SWI_C',...
%     'WQ_DIAG_MAG_MAG_SWI_N',...
%     'WQ_DIAG_MAG_MAG_SWI_P',...
%     'WQ_DIAG_MAG_TMALG',...
%     'WQ_DIAG_MAG_IN',...
%     'WQ_DIAG_MAG_IP',...
%     'WQ_DIAG_MAG_MAG_BEN',...
%     'WQ_DIAG_MAG_IP_BEN',...
%     'WQ_DIAG_MAG_IN_BEN',...
%     'WQ_MAG_ULVA',...
%     'WQ_MAG_ULVA_C',...
%     'WQ_MAG_ULVA_C_IN',...
%     'WQ_MAG_ULVA_C_IP',...
%     'WQ_DIAG_MAG_GPP',...
%     'WQ_DIAG_MAG_PUP',...
%     'WQ_DIAG_MAG_NUP',...
%     'WQ_DIAG_MAG_NMP',...
%     'WQ_DIAG_MAG_GPP_BEN',...
%     'WQ_DIAG_MAG_RSP_BEN',...
%     'WQ_DIAG_MAG_PUP_BEN',...
%     'WQ_DIAG_MAG_NUP_BEN',...
%     'WQ_DIAG_MAG_NMP_BEN',...
%     'WQ_DIAG_MAG_SLG_BEN',...
%     'WQ_DIAG_NCS_RESUS',...
%     'WQ_DIAG_MAC_GPP',...
%     'WQ_DIAG_MAC_NPP',...
%     'WQ_DIAG_MAC_MAC_BEN',...
    };

phys={'GRN','CRYPT','DIATOM','DINO'};
proc={'GPP','RSP','EXC','MOR','SET'};
nut ={'C','N','P'}; %nut ={'N'}; %

inc=length(vars);

for mm=1:length(phys)
    for nn=1:length(proc)
        for ll=1:length(nut)
            inc=inc+1;
            vars{inc}=['WQ_DIAG_PHY_',phys{mm},'_',proc{nn},'_',nut{ll}];
        end
    end
end