
vars = {...
    'D',...
    'WQ_DIAG_TOT_TN'               ,...
    'WQ_NIT_AMM'                   ,...
    'WQ_NIT_NIT'                   ,...
    'WQ_DIAG_NIT_AMM_DSF',...
    'WQ_DIAG_NIT_NIT_DSF',...
    'WQ_DIAG_NIT_SED_AMM'          ,...
    'WQ_DIAG_NIT_SED_NIT'          ,...
    'WQ_DIAG_NIT_NITRIF'           ,...
    'WQ_DIAG_NIT_DENIT'            ,...
    'WQ_DIAG_NIT_ANAMMOX'          ,...
    'WQ_DIAG_NIT_DNRA'             ,...
    'WQ_DIAG_NIT_DIN_ATM'     ,...
   };